"""sitemap_pages

Revision ID: 412d7efc59c3
Revises:
Create Date: 2024-02-20 16:14:25.927325

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '412d7efc59c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitemap_model',
                    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, primary_key=True, nullable=False),
                    sa.Column('status', mysql.MEDIUMINT(unsigned=True), server_default=sa.text('0'), nullable=False,
                              unique=False, index=True),
                    sa.Column('sitemap_url', sa.String(255), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP, nullable=False,
                              server_default=sa.text("CURRENT_TIMESTAMP")),
                    sa.Column('updated_at', sa.TIMESTAMP, nullable=False, index=False, unique=False,
                              server_onupdate=sa.text("CURRENT_TIMESTAMP"),
                              server_default=sa.text("CURRENT_TIMESTAMP")),
                    sa.Column('priority', mysql.MEDIUMINT(unsigned=True), index=True, nullable=True),
                    sa.Column('attempt', mysql.MEDIUMINT(unsigned=True), nullable=True,
                              server_default=sa.sql.expression.text("0")),
                    sa.Column('exception', mysql.TEXT(), nullable=True, unique=False),
                    )
    op.create_index(op.f('ix_sitemap_pages_sitemap_url'), 'sitemap_model', ['sitemap_url'], unique=False)
    op.create_index(op.f('ix_sitemap_attempt'), 'sitemap_model', ['attempt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sitemap_pages_sitemap_url'), table_name='sitemap_model')
    op.drop_index(op.f('ix_sitemap_attempt'), table_name='sitemap_model')
    op.drop_table('sitemap_model')
    # ### end Alembic commands ###
