"""info_page

Revision ID: d8a57762ed94
Revises: 412d7efc59c3
Create Date: 2024-02-21 16:33:55.756313

"""
import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8a57762ed94'
down_revision = '412d7efc59c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_page',
                    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, primary_key=True, nullable=False),
                    sa.Column('status', mysql.MEDIUMINT(unsigned=True), server_default=sa.text('0'), nullable=False,
                              unique=False, index=True),
                    sa.Column('created_at', sa.TIMESTAMP, nullable=False,
                              server_default=sa.text("CURRENT_TIMESTAMP")),
                    sa.Column('updated_at', sa.TIMESTAMP, nullable=False, index=False, unique=False,
                              server_onupdate=sa.text("CURRENT_TIMESTAMP"),
                              server_default=sa.text("CURRENT_TIMESTAMP")),
                    sa.Column('priority', mysql.MEDIUMINT(unsigned=True), index=True, nullable=True),
                    sa.Column('attempt', mysql.MEDIUMINT(unsigned=True), nullable=True,
                              server_default=sa.sql.expression.text("0")),
                    sa.Column('exception', mysql.TEXT(), nullable=True, unique=False),

                    sa.Column('business_id', mysql.BIGINT(), index=True, nullable=False, primary_key=True),
                    sa.Column('business_name', mysql.TEXT()),
                    sa.Column('business_address', mysql.VARCHAR(768)),
                    sa.Column('business_category', mysql.TEXT()),
                    sa.Column('business_web_url', mysql.VARCHAR(768)),
                    sa.Column('business_img_url', mysql.VARCHAR(768)),
                    sa.Column('business_detailed_url', mysql.VARCHAR(768), nullable=False),
                    sa.Column('business_phone', mysql.BIGINT(), index=True),
                    sa.Column('business_fax', mysql.BIGINT(), index=True),
                    sa.Column('business_hours', mysql.JSON()),
                    sa.Column('business_stars', mysql.VARCHAR(255)),
                    sa.Column('business_customer_reviews', mysql.VARCHAR(255)),
                    sa.Column('business_bbb_rating', mysql.VARCHAR(255)),
                    sa.Column('business_accredited_date', mysql.VARCHAR(255)),
                    sa.Column('business_social_media', mysql.JSON()),
                    sa.Column('business_years', mysql.VARCHAR(255)),
                    sa.Column('business_started_date', mysql.VARCHAR(255)),
                    sa.Column('parse_date', mysql.VARCHAR(255)),
                    sa.Column('business_contact_information', mysql.JSON()),
                    sa.Column('business_management', mysql.JSON()),
                    )
    # op.create_index(op.f('ix_info_updated_at'), 'info_page', ['updated_at'], unique=False)
    # op.create_index(op.f('ix_info_priority'), 'info_page', ['priority'], unique=False)
    op.create_index(op.f('ix_info_attempt'), 'info_page', ['attempt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_sitemap_updated_at'), table_name='info_page')
    # op.drop_index(op.f('ix_sitemap_priority'), table_name='info_page')
    op.drop_index(op.f('ix_info_attempt'), table_name='info_page')
    op.drop_table('info_page')
    # ### end Alembic commands ###
