"""info_page

Revision ID: d8a57762ed94
Revises: 412d7efc59c3
Create Date: 2024-02-21 16:33:55.756313

"""
import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8a57762ed94'
down_revision = '412d7efc59c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_page',
                    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, primary_key=True, nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP, nullable=False,
                              server_default=sa.text("CURRENT_TIMESTAMP")),
                    sa.Column('updated_at', sa.TIMESTAMP, nullable=False, index=False, unique=False,
                              server_onupdate=sa.text("CURRENT_TIMESTAMP"),
                              server_default=sa.text("CURRENT_TIMESTAMP")),
                    sa.Column('bbb_id', mysql.VARCHAR(255), index=True, nullable=False, unique=True),
                    sa.Column('name', mysql.TEXT()),
                    sa.Column('address', mysql.VARCHAR(768)),
                    sa.Column('category', mysql.TEXT()),
                    sa.Column('web_url', mysql.VARCHAR(768)),
                    sa.Column('img_url', mysql.VARCHAR(768)),
                    sa.Column('detailed_url', mysql.VARCHAR(768), nullable=False),
                    sa.Column('phone', mysql.BIGINT(), index=True),
                    sa.Column('fax', mysql.BIGINT(), index=True),
                    sa.Column('hours', mysql.JSON()),
                    sa.Column('stars', mysql.VARCHAR(255)),
                    sa.Column('customer_reviews', mysql.VARCHAR(255)),
                    sa.Column('bbb_rating', mysql.VARCHAR(255)),
                    sa.Column('accredited_date', mysql.VARCHAR(255)),
                    sa.Column('social_media', mysql.JSON()),
                    sa.Column('years', mysql.VARCHAR(255)),
                    sa.Column('started_date', mysql.VARCHAR(255)),
                    sa.Column('parse_date', mysql.VARCHAR(255)),
                    sa.Column('contact_information', mysql.JSON()),
                    sa.Column('management', mysql.JSON()),
                    sa.Column('sent_to_customer', mysql.VARCHAR(255), ),
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info_page')
    # ### end Alembic commands ###
