"""info_page

Revision ID: d8a57762ed94
Revises: 412d7efc59c3
Create Date: 2024-02-21 16:33:55.756313

"""
import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8a57762ed94'
down_revision = '412d7efc59c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info_page',
                    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, primary_key=True, nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP, nullable=False,
                              server_default=sa.text("CURRENT_TIMESTAMP")),
                    sa.Column('updated_at', sa.TIMESTAMP, nullable=False, index=False, unique=False,
                              server_onupdate=sa.text("CURRENT_TIMESTAMP"),
                              server_default=sa.text("CURRENT_TIMESTAMP")),

                    sa.Column('business_id', mysql.BIGINT(), index=True, nullable=False, primary_key=True),
                    sa.Column('business_name', mysql.TEXT()),
                    sa.Column('business_address', mysql.VARCHAR(768)),
                    sa.Column('business_category', mysql.TEXT()),
                    sa.Column('business_web_url', mysql.VARCHAR(768)),
                    sa.Column('business_img_url', mysql.VARCHAR(768)),
                    sa.Column('business_detailed_url', mysql.VARCHAR(768), nullable=False),
                    sa.Column('business_phone', mysql.BIGINT(), index=True),
                    sa.Column('business_fax', mysql.BIGINT(), index=True),
                    sa.Column('business_hours', mysql.JSON()),
                    sa.Column('business_stars', mysql.VARCHAR(255)),
                    sa.Column('business_customer_reviews', mysql.VARCHAR(255)),
                    sa.Column('business_bbb_rating', mysql.VARCHAR(255)),
                    sa.Column('business_accredited_date', mysql.VARCHAR(255)),
                    sa.Column('business_social_media', mysql.JSON()),
                    sa.Column('business_years', mysql.VARCHAR(255)),
                    sa.Column('business_started_date', mysql.VARCHAR(255)),
                    sa.Column('parse_date', mysql.VARCHAR(255)),
                    sa.Column('business_contact_information', mysql.JSON()),
                    sa.Column('business_management', mysql.JSON()),
                    sa.Column('sent_to_customer', mysql.VARCHAR(255), ),
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info_page')
    # ### end Alembic commands ###
